/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.42
 * Generated at: 2025-11-19 06:55:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class input_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPではGET、POST、またはHEADのみが許可されます。 JasperはOPTIONSも許可しています。");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("  <link rel=\"stylesheet\"  href=\"http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css\">\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=M+PLUS+Rounded+1c\" rel=\"stylesheet\">\n");
      out.write("  <link rel=\"stylesheet\"  href=\"css/input.css\">\n");
      out.write("  \n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<body>\n");
      out.write("        <header>\n");
      out.write("        <div id=\"header\">\n");
      out.write("            <a href=\"#\">キャンセル</a>\n");
      out.write("            <h1>XX年XX月</h1>\n");
      out.write("            <a href=\"#\">保存</a>\n");
      out.write("        </div>\n");
      out.write("    </header>\n");
      out.write("        <div id=\"container\">\n");
      out.write("        <form id=\"form\">\n");
      out.write("            <div id=\"title\">\n");
      out.write("            <label for=\"title\">タイトル：</label>\n");
      out.write("            <input type=\"text\" name=\"title\">\n");
      out.write("            </div>\n");
      out.write("            <div id=\"type\">\n");
      out.write("            <label for=\"type\">種類：</label>\n");
      out.write("            <select name=\"type\">\n");
      out.write("                <option value=\"private\">個人</option>\n");
      out.write("                <option value=\"job\">仕事</option>\n");
      out.write("                <option value=\"family\">家族</option>\n");
      out.write("            </select>\n");
      out.write("            </div>\n");
      out.write("            <div id=\"color\">\n");
      out.write("            <label for=\"color\">色：</label>\n");
      out.write("                <input type=\"radio\" name=\"color\" value=\"red\" style=\"accent-color: #FFCCCC\">\n");
      out.write("                <input type=\"radio\" name=\"color\" value=\"blue\" style=\"accent-color: #CCE5FF;\">\n");
      out.write("                <input type=\"radio\" name=\"color\" value=\"green\" style=\"accent-color: #E6FFCC;\">\n");
      out.write("                <input type=\"radio\" name=\"color\" value=\"pink\" style=\"accent-color: pink\">\n");
      out.write("                <input type=\"radio\" name=\"color\" value=\"gray\" style=\"accent-color: gray\">\n");
      out.write("            </div>\n");
      out.write("            <div id=\"all_day\">\n");
      out.write("            <label for=\"all_day\">終日</label>\n");
      out.write("                <input type=\"checkbox\" name=\"one_day\" value=\"one_day\">\n");
      out.write("            </div>\n");
      out.write("            <div id=\"start_day\">\n");
      out.write("            <label for=\"start_day\">開始</label>\n");
      out.write("                <P>XX月XX日</P>\n");
      out.write("            </div>\n");
      out.write("            <div id=\"goal_day\">\n");
      out.write("            <label for=\"goal_day\">終了</label>\n");
      out.write("                <p><a href=\"#\">XX月XX日</a></p>\n");
      out.write("            </div>\n");
      out.write("            <div id=\"repeat\">\n");
      out.write("            <label for=\"repeat\">繰り返し</label>\n");
      out.write("            <select>\n");
      out.write("                <option value=\"every_day\">毎日</option>\n");
      out.write("                <option value=\"every_week\">毎週</option>\n");
      out.write("                <option value=\"every_month\">毎月</option>\n");
      out.write("                <option value=\"every_year\">毎年</option>\n");
      out.write("            </select>\n");
      out.write("            </div>\n");
      out.write("            <!-- 詳細画面拡張 -->\n");
      out.write("            <div class=\"columns\">\n");
      out.write("                <div class=\"column m-3\">\n");
      out.write("                    <div class=\"card\">\n");
      out.write("                        <header class=\"card-header\">\n");
      out.write("                            <p class=\"card-header-title\">メモ帳詳細</p>\n");
      out.write("                            <button class=\"card-header-icon\" aria-label=\"more options\" onclick=\"toggleCard(this)\">↴\n");
      out.write("                                <span class=\"icon\">\n");
      out.write("                                    <i class=\"fas fa-angle-down\" aria-hidden=\"true\"></i>\n");
      out.write("                                </span>\n");
      out.write("                            </button>\n");
      out.write("                        </header>\n");
      out.write("                        <div class=\"card-content\" style=\"display: none;\">\n");
      out.write("                            <div class=\"text_table\">\n");
      out.write("                                <input type=\"textarea\" name=\"msg\" cols=\"40\" rows=\"4\" placeholder=\"書き出し/タイトル\">\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"card\">\n");
      out.write("                        <header class=\"card-header\"><p class=\"card-header-title\">家計簿詳細</p>\n");
      out.write("                            <button class=\"card-header-icon\" aria-label=\"more options\" onclick=\"toggleCard(this)\">↴\n");
      out.write("                                <span class=\"icon\">\n");
      out.write("                                    <i class=\"fas fa-angle-down\" aria-hidden=\"true\"></i>\n");
      out.write("                                </span>\n");
      out.write("                            </button>\n");
      out.write("                        </header>\n");
      out.write("                        <div class=\"card-content\" style=\"display: none;\">\n");
      out.write("                            <div class=\"content\">\n");
      out.write("                                <form>\n");
      out.write("                                    <div class=\"expenses\">\n");
      out.write("                                    <input type=\"radio\" name=\"expenses\" value=\"out\" checked>支出\n");
      out.write("                                    <input type=\"radio\" name=\"expenses\" value=\"in\">収入\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"amount\">\n");
      out.write("                                        <label for=\"amount\">金額</label>\n");
      out.write("                                        <input type=\"number\" name=\"number\" min=\"0\" value=\"0\" step=\"1\">\n");
      out.write("                                    </div>\n");
      out.write("                                    <label for=\"category\">カテゴリー</label>\n");
      out.write("                                    <div class=\"category\">\n");
      out.write("                                        <input type=\"radio\" name=\"button\" value=\"private_radio\">個人\n");
      out.write("                                        <input type=\"radio\" name=\"button\" value=\"job_radio\">仕事\n");
      out.write("                                        <input type=\"radio\" name=\"button\" value=\"family_radio\">家族\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"expenses_title\">\n");
      out.write("                                        <label for=\"expenses_title\">タイトル</label>\n");
      out.write("                                        <input type=\"text\" name=\"expenses_title\">\n");
      out.write("                                    </div>\n");
      out.write("                                </form>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"card\">\n");
      out.write("                        <header class=\"card-header\"><p class=\"card-header-title\">予算表詳細</p>\n");
      out.write("                            <button class=\"card-header-icon\" aria-label=\"more options\" onclick=\"toggleCard(this)\">↴\n");
      out.write("                                <span class=\"icon\">\n");
      out.write("                                    <i class=\"fas fa-angle-down\" aria-hidden=\"true\"></i>\n");
      out.write("                                </span>\n");
      out.write("                            </button>\n");
      out.write("                        </header>\n");
      out.write("                        <div class=\"card-content\" style=\"display: none;\">\n");
      out.write("                            <div class=\"content\">\n");
      out.write("                                <form>\n");
      out.write("                                    <div class=\"expenses\">\n");
      out.write("                                    <input type=\"radio\" name=\"expenses\" value=\"out\" checked>支出\n");
      out.write("                                    <input type=\"radio\" name=\"expenses\" value=\"in\">収入\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"amount\">\n");
      out.write("                                        <label for=\"amount\">金額</label>\n");
      out.write("                                        <input type=\"number\" name=\"number\" min=\"0\" value=\"0\" step=\"1\">\n");
      out.write("                                    </div>\n");
      out.write("                                    <label for=\"category\">カテゴリー</label>\n");
      out.write("                                    <div class=\"category\">\n");
      out.write("                                        <input type=\"radio\" name=\"button\" value=\"private_radio\">個人\n");
      out.write("                                        <input type=\"radio\" name=\"button\" value=\"job_radio\">仕事\n");
      out.write("                                        <input type=\"radio\" name=\"button\" value=\"family_radio\">家族\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"expenses_title\">\n");
      out.write("                                        <label for=\"expenses_title\">タイトル</label>\n");
      out.write("                                        <input type=\"text\" name=\"expenses_title\">\n");
      out.write("                                    </div>\n");
      out.write("                                </form>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("            <!--  -->\n");
      out.write("            <!-- <div id=\"add_table\">\n");
      out.write("            <label for=\"text_table\">メモ帳詳細</label>\n");
      out.write("                <button id=\"add\" type=\"button\">✙</button>\n");
      out.write("            </div>\n");
      out.write("            <div id=\"add_table\">\n");
      out.write("            <label for=\"expenses_table\">家計簿詳細</label>\n");
      out.write("                <button id=\"add\" type=\"button\">✙</button>\n");
      out.write("            </div>\n");
      out.write("            <div id=\"add_table\">\n");
      out.write("            <label for=\"budget_table\">予算表詳細</label>\n");
      out.write("                <button id=\"add\" type=\"button\">✙</button>\n");
      out.write("            </div> -->\n");
      out.write("        </form>\n");
      out.write("        </div>\n");
      out.write("</body>\n");
      out.write("<script>\n");
      out.write("    function toggleCard(button) {\n");
      out.write("  // 全てのカードコンテンツを取得\n");
      out.write("const allCardContents = document.querySelectorAll('.card-content');\n");
      out.write("const allIcons = document.querySelectorAll('.card-header-icon i');\n");
      out.write("\n");
      out.write("  // クリックされたカードのコンテンツとアイコンを取得\n");
      out.write("const clickedCardContent = button.closest('.card').querySelector('.card-content');\n");
      out.write("const clickedIcon = button.querySelector('i');\n");
      out.write("  // クリックされたカードの状態を退避\n");
      out.write("var cardStatus = clickedCardContent.style.display;\n");
      out.write("\n");
      out.write("  // まず全てのカードを閉じる\n");
      out.write("// 一度開いたら閉じないようにする\n");
      out.write("// allCardContents.forEach(content => {\n");
      out.write("//     content.style.display = 'none';\n");
      out.write("// });\n");
      out.write("allIcons.forEach(icon => {\n");
      out.write("    icon.classList.remove('fa-angle-up');\n");
      out.write("    icon.classList.add('fa-angle-down');\n");
      out.write("});\n");
      out.write("\n");
      out.write("if (cardStatus === 'none') {\n");
      out.write("    // クリックされたカードが閉じていた場合は開く\n");
      out.write("    clickedCardContent.style.display = 'block';\n");
      out.write("    clickedIcon.classList.remove('fa-angle-down');\n");
      out.write("    clickedIcon.classList.add('fa-angle-up');\n");
      out.write("} else {\n");
      out.write("    // クリックされたカードが開いていた場合は閉じる\n");
      out.write("    clickedCardContent.style.display = 'none';\n");
      out.write("    clickedIcon.classList.remove('fa-angle-up');\n");
      out.write("    clickedIcon.classList.add('fa-angle-down');\n");
      out.write("}\n");
      out.write("}\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
